# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-03 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_up',
            field=models.DateField(blank=True, null=True),
        ),
    ]
