# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-05 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(upload_to='upload-product/'),
        ),
    ]
